---
- hosts: all
  user: vagrant
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: yum update
    yum: name='*' state=latest
  - name:  install python2-pip epel wget bind-utils rsync
    yum: name=python2-pip.noarch,epel-release,wget,bind-utils,rsync state=latest
