Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "~/git_repo", "/git_repo"
  config.ssh.insert_key = false
    config.vm.provision "ansible_local" do |ansible|
       ansible.verbose = "v"
       ansible.playbook = "provision_centos7_vagrant.yml"
    config.vm.provision "shell" do | shell|
      shell.inline = "pip install requests awscli boto3"
    end
  end
end

